name: Build JSON

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build JSON
      run: |
        ./data_processor.rb
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: viz-data
        path: viz_data.json